### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by wayhome** [iovxw/rssbot#66]
以下是基于目前 master  db46486a0e16c44f4d89d0976f6cc334718f5e6b 的报错：

```Apr 29 09:06:27 bwg01 systemd[1]: Started rssbot.
Apr 29 09:06:29 bwg01 rssbot[10656]: thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/handlers/mod.rs:66:23
Apr 29 09:06:29 bwg01 rssbot[10656]: stack backtrace:
Apr 29 09:06:29 bwg01 rssbot[10656]:    0:     0x5586c9d1fbd4 - backtrace::backtrace::libunwind::trace::h94e9dfaa8e5bf169
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
Apr 29 09:06:29 bwg01 rssbot[10656]:    1:     0x5586c9d1fbd4 - backtrace::backtrace::trace_unsynchronized::ha07ffabc89bfba55
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Apr 29 09:06:29 bwg01 rssbot[10656]:    2:     0x5586c9d1fbd4 - std::sys_common::backtrace::_print_fmt::hf0ddae3c006ddd6a
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/sys_common/backtrace.rs:78
Apr 29 09:06:29 bwg01 rssbot[10656]:    3:     0x5586c9d1fbd4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bed8846a94c354
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/sys_common/backtrace.rs:59
Apr 29 09:06:29 bwg01 rssbot[10656]:    4:     0x5586c9d475dc - core::fmt::write::h322ad484477a3f83
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libcore/fmt/mod.rs:1069
Apr 29 09:06:29 bwg01 rssbot[10656]:    5:     0x5586c9d198f3 - std::io::Write::write_fmt::hac4f5f7752010be3
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/io/mod.rs:1504
Apr 29 09:06:29 bwg01 rssbot[10656]:    6:     0x5586c9d22665 - std::sys_common::backtrace::_print::h4762bdaa8e596629
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/sys_common/backtrace.rs:62
Apr 29 09:06:29 bwg01 rssbot[10656]:    7:     0x5586c9d22665 - std::sys_common::backtrace::print::h3a936825b19f51cd
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/sys_common/backtrace.rs:49
Apr 29 09:06:29 bwg01 rssbot[10656]:    8:     0x5586c9d22665 - std::panicking::default_hook::{{closure}}::hcef47dacac4268f9
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/panicking.rs:198
Apr 29 09:06:29 bwg01 rssbot[10656]:    9:     0x5586c9d223a2 - std::panicking::default_hook::h330e0256b207ac65
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/panicking.rs:218
Apr 29 09:06:29 bwg01 rssbot[10656]:   10:     0x5586c97f289e - rssbot::enable_fail_fast::{{closure}}::h11a15ab0069863c0
Apr 29 09:06:29 bwg01 rssbot[10656]:   11:     0x5586c9d22d95 - std::panicking::rust_panic_with_hook::h708da68555d85799
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/panicking.rs:515
Apr 29 09:06:29 bwg01 rssbot[10656]:   12:     0x5586c9d228ab - rust_begin_unwind
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/panicking.rs:419
Apr 29 09:06:29 bwg01 rssbot[10656]:   13:     0x5586c9d45d51 - core::panicking::panic_fmt::hde3b05374283390d
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libcore/panicking.rs:111
Apr 29 09:06:29 bwg01 rssbot[10656]:   14:     0x5586c9d45c9d - core::panicking::panic::he6e8c5f36f1e6537
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libcore/panicking.rs:54
Apr 29 09:06:29 bwg01 rssbot[10656]:   15:     0x5586c975c009 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0e51546f3f914517
Apr 29 09:06:29 bwg01 rssbot[10656]:   16:     0x5586c9810f75 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9a1e589b4170ab64
Apr 29 09:06:29 bwg01 rssbot[10656]:   17:     0x5586c97d699e - tokio::runtime::task::harness::Harness<T,S>::poll::ha48bc4033e4c3f93
Apr 29 09:06:29 bwg01 rssbot[10656]:   18:     0x5586c9caac5b - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::h27f4d6cec5d57cc1
Apr 29 09:06:29 bwg01 rssbot[10656]:   19:     0x5586c9caab93 - tokio::runtime::thread_pool::worker::Context::run_task::hd221adeb1f1826d2
Apr 29 09:06:29 bwg01 rssbot[10656]:   20:     0x5586c9caa399 - tokio::runtime::thread_pool::worker::Context::run::h07b2bb4b9a39bc05
Apr 29 09:06:29 bwg01 rssbot[10656]:   21:     0x5586c9c9d3f3 - tokio::macros::scoped_tls::ScopedKey<T>::set::h90b15767eefc2a0e
Apr 29 09:06:29 bwg01 rssbot[10656]:   22:     0x5586c9ca9a8e - tokio::runtime::thread_pool::worker::run::h08e68ea1bbcacf5f
Apr 29 09:06:29 bwg01 rssbot[10656]:   23:     0x5586c9ca0dcb - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h08312341c611b588
Apr 29 09:06:29 bwg01 rssbot[10656]:   24:     0x5586c9cab7e5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha68c9e604fbc136d
Apr 29 09:06:29 bwg01 rssbot[10656]:   25:     0x5586c9cb2656 - tokio::runtime::task::harness::Harness<T,S>::poll::h879e78c487e88df0
Apr 29 09:06:29 bwg01 rssbot[10656]:   26:     0x5586c9c9f1c7 - tokio::runtime::blocking::pool::Inner::run::h5658f52a31076fb2
Apr 29 09:06:29 bwg01 rssbot[10656]:   27:     0x5586c9c98ce8 - tokio::runtime::context::enter::h5242f691bce74353
Apr 29 09:06:29 bwg01 rssbot[10656]:   28:     0x5586c9c94ecf - std::sys_common::backtrace::__rust_begin_short_backtrace::h60859ea46a51dcd2
Apr 29 09:06:29 bwg01 rssbot[10656]:   29:     0x5586c9ca4282 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4d5a7fdbfb3646df
Apr 29 09:06:29 bwg01 rssbot[10656]:   30:     0x5586c9d2594a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he68d47c8d6913d69
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/liballoc/boxed.rs:1008
Apr 29 09:06:29 bwg01 rssbot[10656]:   31:     0x5586c9d2594a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha8bba21f7fb85e86
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/liballoc/boxed.rs:1008
Apr 29 09:06:29 bwg01 rssbot[10656]:   32:     0x5586c9d2594a - std::sys::unix::thread::Thread::new::thread_start::h055b5940b53f7ba8
Apr 29 09:06:29 bwg01 rssbot[10656]:                                at src/libstd/sys/unix/thread.rs:87
Apr 29 09:06:29 bwg01 rssbot[10656]:   33:     0x7f655911d6db - start_thread
Apr 29 09:06:29 bwg01 rssbot[10656]:   34:     0x7f6558c2e88f - __clone
Apr 29 09:06:29 bwg01 rssbot[10656]:   35:                0x0 - <unknown>
Apr 29 09:06:29 bwg01 systemd[1]: rssbot.service: Main process exited, code=exited, status=101/n/a```

**Comment by iovxw** [comment]
不应在 channel 中使用命令，我加了个提示
